on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: backup
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:lxy_jdsy/lxy_jdsy.git
          ssh_private_key: ${{ secrets.GITEE_KEY }}
